name: CI

on:
  push:
    branches:
      - implementacao

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install selenium
        pip install PyPDF2

    - name: Run Tests and Coverage
      run: |
        pytest --cov=your_module --cov-report=xml
        cc-test-reporter format-coverage --input-type coverage.py --output .coverage/codeclimate.json
        cc-test-reporter upload-coverage
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.Test_Reporter }}

    - name: Code Climate Quality Check
      run: cc-test-reporter sum-coverage -p 1

    - name: Run Code Climate Checks
      run: cc-test-reporter upload-coverage
