site_name: MDS-Squad08
site_url: https://unb-mds.github.io/2023-2-Squad08/
theme:
  name: material
nav:
  - Comece por aqui :): "index.md"
  - Backlog: "Backlog.md"
  - Gestão do Projeto:
    - Arquitetura: "Gestão do Projeto/Arquitetura.md"
    - Comunicação: "Gestão do Projeto/Comunicação.md"
    - MVV: "Gestão do Projeto/MVV.md"
    - Personas : "Gestão do Projeto/PersonasQD.md"
    - Storymap: "Gestão do Projeto/Storymap.md"
    - Design Sprint:
      - O que é: "DesignSprint/DesignSprint.md"
      - Decidir: "DesignSprint/Decidir.md"
      - Design: "DesignSprint/Design.md"
      - Ideação: "DesignSprint/Ideação.md"
      - Mapeamento: "DesignSprint/Mapeamento.md"
      - Requisitos: "DesignSprint/Requisitos.md"
  - Políticas:
    - Branches: "Políticas/Branches.md"
    - Código de conduta: "Políticas/Código de conduta.md"
    - Commits: "Políticas/Commits.md"
    - Issues: "Políticas/Issues.md"
  - Tecnologias:
    - Escolhas Tecnológicas: "Tecnologias/EscolhasTecnologicas.md"
  - Sprints:
    - Sprint 00: 
      - Planejamento: "Sprints/Sprint00/Planejamento.md"
      - Resultados: "Sprints/Sprint00/Resultados.md"
    - Sprint 01: 
      - Planejamento: "Sprints/Sprint01/Planejamento.md"
      - Resultados: "Sprints/Sprint01/Resultados.md"
    - Sprint 02:
      - Planejamento: "Sprints/Sprint02/Planejamento.md"
      - Resultados: "Sprints/Sprint02/Resultados.md"
    - Sprint 03:
      - Planejamento: "Sprints/Sprint03/Planejamento.md"
      - Resultados: "Sprints/Sprint03/Resultados.md"
    - Sprint 04:
      - Planejamento: "Sprints/Sprint04/Planejamento.md"
      - Resultados: "Sprints/Sprint04/Resultados.md"
    - Sprint 05:
      - Planejamento: "Sprints/Sprint05/Planejamento.md"
      - Resultados: "Sprints/Sprint05/Resultados.md"
    - Sprint 06:
      - Planejamento: "Sprints/Sprint06/Planejamento.md"
      - Resultados: "Sprints/Sprint06/Resultados.md"
    - Sprint 07:
      - Planejamento: "Sprints/Sprint07/Planejamento.md"
      - Resultados: "Sprints/Sprint07/Resultados.md"
    - Sprint 08:
      - Planejamento: "Sprints/Sprint08/Planejamento.md"
      - Resultados: "Sprints/Sprint08/Resultados.md"
    - Sprint 09:
      - Planejamento: "Sprints/Sprint09/Planejamento.md"
      - Resultados: "Sprints/Sprint09/Resultados.md"
    - Sprint 10:
      - Planejamento: "Sprints/Sprint10/Planejamento.md"
      - Resultados: "Sprints/Sprint10/Resultados.md"
    - Sprint 11:
      - Planejamento: "Sprints/Sprint11/Planejamento.md"
      - Resultados: "Sprints/Sprint11/Resultados.md"
    



