name: Python CI

on:
  pull_request:
  push:
    branches:
      - implementacao
  

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Instalando o Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install selenium
        pip install PyPDF2
        

    - name: Run Pylint
      run: |
        pylint Camada_Dados/ExtrairJson.py
        pylint Camada_Dados/Regex.py
        pylint Camada_Dados/WebScraper.py
