name: Test Coverage

on: 
    push:
        branches:
            - front-end

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
        - name: Publish code coverage
          uses: paambaati/codeclimate-action@v3.0.0
          env:
            CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }} 
